# Generated by Django 5.0.4 on 2024-05-22 20:10

import APP.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=200, null=True)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='hostels/')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=200)),
                ('breakfast_description', models.CharField(max_length=200)),
                ('breakfast_image', models.ImageField(upload_to='breakfasts/')),
                ('lunch_description', models.CharField(max_length=200)),
                ('lunch_image', models.ImageField(upload_to='lunches/')),
                ('dinner_description', models.CharField(max_length=200)),
                ('dinner_image', models.ImageField(upload_to='dinners/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('reg_number', models.IntegerField(default=0, null=True)),
                ('Email_address', models.CharField(max_length=100, null=True)),
                ('contact_no', models.IntegerField(default=0, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=200, null=True)),
                ('Father_name', models.CharField(max_length=200, null=True)),
                ('Father_email_address', models.CharField(max_length=200, null=True)),
                ('Father_contact_no', models.IntegerField(default=0, null=True)),
                ('Mother_name', models.CharField(max_length=200, null=True)),
                ('Mother_email_address', models.CharField(max_length=200, null=True)),
                ('Mother_contact_no', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, null=True)),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floors', to='APP.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=200)),
                ('max_capacity', models.IntegerField(default=1)),
                ('current_bookings', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Vacant', 'Vacant'), ('Full', 'Full'), ('Maintainece', 'Maintainece')], max_length=200)),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='APP.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(default=datetime.date.today)),
                ('check_out', models.DateField(default=APP.models.get_end_of_semester)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APP.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APP.user')),
            ],
        ),
    ]
