# Generated by Django 5.0.4 on 2024-05-19 19:26

import APP.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reg_number', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=200)),
                ('max_capacity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Vacant', 'Vacant'), ('Full', 'Full'), ('Maintainece', 'Maintainece')], max_length=200)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='APP.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(default=datetime.date.today)),
                ('check_out', models.DateField(default=APP.models.get_end_of_semester)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.user')),
            ],
        ),
    ]
