# Generated by Django 5.0.4 on 2024-05-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_hostel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
