# Generated by Django 5.0.4 on 2024-05-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_remove_booking_user_booking_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='student',
            new_name='user',
        ),
    ]
