# Generated by Django 5.0.4 on 2024-05-20 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_alter_booking_room_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hostel',
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APP.hostel')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='APP.floor'),
        ),
    ]
