# Generated by Django 5.0.4 on 2024-05-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_rename_student_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='student',
        ),
    ]
