# Generated by Django 5.0.4 on 2024-05-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_remove_room_hostel_floor_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_bookings',
            field=models.IntegerField(default=0),
        ),
    ]
