# Generated by Django 5.0.4 on 2024-05-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_room_current_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Email_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Father_contact_no',
            field=models.IntegerField(default=975, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Father_email_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Father_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Mother_contact_no',
            field=models.IntegerField(default=975, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Mother_email_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Mother_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.IntegerField(default=975, null=True),
        ),
    ]
