# Generated by Django 5.0.4 on 2024-05-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_user_email_address_user_father_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Father_contact_no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Mother_contact_no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
