# Generated by Django 5.0.4 on 2024-05-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_alter_user_father_contact_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hostel_description',
        ),
    ]
