# Generated by Django 5.0.4 on 2024-05-21 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_delete_hostel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floors', to='APP.hostel'),
        ),
    ]
