# Generated by Django 5.0.4 on 2024-05-26 15:06

import APP.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0012_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(blank=True, default=APP.models.get_end_of_semester),
        ),
    ]
