# Generated by Django 5.0.4 on 2024-05-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('block', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='counselors/')),
            ],
        ),
    ]
