# Generated by Django 5.0.4 on 2024-05-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0017_remove_userprofile_profile_pic_alter_floor_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(max_length=200),
        ),
    ]
